spring:
#  mvc:
#   static-path-pattern: /**
#    view:
#      prefix: /static/
#      suffix: .html
#  thymeleaf:
#    prefix: classpath:/static/**
  datasource:
    url: jdbc:mysql://192.168.1.109:3306/smart_tray?zeroDateTimeBehavior=convertToNull&amp;characterEncoding=UTF8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:/sqlmap/**.xml
  typeAliasesPackage: com.smartcold.tray.mapper
  type-aliases-package: com.smartcold.tray.entity

server:
  port: 8888
  tomcat:
    uri-encoding: utf-8

